# Generated by Django 3.2.7 on 2021-10-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'рубрика',
                'verbose_name_plural': 'рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-published'], 'verbose_name': 'обьявление', 'verbose_name_plural': 'обьявления'},
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, default='Типо текс', help_text='основное поле', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(blank=True, help_text='поле цены', null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='поле даты', verbose_name='Опубликованно'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(default='Типо заголовок', help_text='поле заголовка', max_length=50, unique=True, verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='bb',
            name='rubrik',
            field=models.ForeignKey(help_text='поле рубрики', null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubrik', verbose_name='Рубрика'),
        ),
    ]
